# wrangler.toml
name = "reader-cloudflare"
main = "functions/[[path]].ts"
pages_build_output_dir = "public"
account_id = "..."

[[r2_buckets]]
binding = "R2"
bucket_name = "reader-files"

[[d1_databases]]
binding = "DB"
database_name = "reader-db"
database_id = "..."

[vars]
APP_ORIGIN = "https://reader-cloudflare-starter.pages.dev"   # <-- exact production URL
AUTH_SECRET = "<your long base64 secret here>"               # use your generated one
EMAIL_FROM = "login@readthem.online"                         # any address for now
TURNSTILE_SECRET = ""
