name = "reader-cloudflare"
main = "functions/[[path]].ts"
pages_build_output_dir = "public"

[[r2_buckets]]
binding = "R2"                 # <-- code uses env.R2
bucket_name = "reader-files"

[[d1_databases]]
binding = "DB"                 # <-- code uses env.DB
database_name = "reader-db"
database_id = "3144c252-7090-4997-8475-49591ca38e8e"  # your real ID

[vars]
APP_ORIGIN = "https://reader-cloudflare-starter.pages.dev"
AUTH_SECRET = "+waB73pQm6pHSF1MRrtN3B3EPwGz+WQwyD0nGTDOs9ljB8J40rKrfLOECancZNWs"
EMAIL_FROM  = "reeeeedbox@gmail.com"
TURNSTILE_SECRET = ""
